const string = {
  ar: {
    hello: "مرحبا",
    mainPage: "الصفحة الرئيسية",
    lang: "English",
    footerEnd: "جميع الحقوق محفوظة 2020 - ماي تكت",
    mainPagePath: "الرئيسية",
    showsPagePath: "فعاليات",
    ticketsTypes: "فئات التذاكر",
    selectTicketDefault: "تحديد أحد الخيارات",
    chooseTicketDate: "اختر التاريخ الذي تفضله :",
    chooseTicketTime: "اختر الزمن الذي تفضله :",
    currency: "ر.س",
    chooseDate: "أختيار الالتاريخ",
    chooseTiem: "أختيار الزمن",
    chooseTicketsNumber: "أختيار عدد التذاكر",
    informationTab: "معلومات الفعالية",
    description: "الوصف",
    bookNow: "أحجز الان",
    fromHour: "من الساعة",
    toHour: "إلي الساعة",
    From: "من",
    to: "إلي",
    from: "من",
    Saturday: "السبت",
    Sunday: "الأحد",
    Monday: "الأتنين",
    Tuesday: "الثلاثاء",
    Wednesday: "الأربعاء",
    Thursday: "الخميس",
    Friday: "الجمعة",
    0: "السبت",
    1: "الأحد",
    2: "الإثنين",
    3: "الثلاثاء",
    4: "الأربعاء",
    5: "الخميس",
    6: "الجمعة",
    and: "و",
    bookingDate: "موعد الحجز",
    startFrom: "ابتداء من",
    until: "حتى",
    t: "ل",
    "00": "لسبت",
    11: "لأحد",
    22: "لإثنين",
    33: "لثلاثاء",
    44: "لأربعاء",
    55: "لخميس",
    66: "لجمعة",
    eventName: "أسم الفعالية",
    city: "المدينة",
    date: "التاريخ",
    time: "الزمن",
    address: "العنوان",
    organizer: "منظم الفعالية",
    rating: "التقييم",
    ChoosePayment: "دفع",
    done: "تم",
    cardNumber: "الرقم البطاقة",
    holderName: "أسم صاحب البطاقة",
    expireDate: "أنتهاء الصلاحية",
    ticketPriceErrMessage: "من فضلك قم بأختيار نوع التذكرة",
    chooseDateErrMEssage: "من فضلك قم بأختيار التاريخ",
    chooseSpecificTimeErrMessage: "من فضلك قم بأختيار الزمن",
    chooseTicketCountErrMessage: "من فضلك قم بأختيار عدد التذاكر",
    errMessage:
      "الصفحة التي تبحث عنها غير موجودة أو بها خطأ, الرجاء المحاولة لاحقا",
    PromoCode: "كود الخصم",
    PromoCodeErrMessage: "من فضلك قم بأدخال كود الخصم",
    loading: "جاري التحميل",
    Apply: "تطبيق",
    promoCodeSuccess: "تم تطبيق الكود بنجاح",
  },
  en: {
    hello: "Hello",
    mainPage: "Main Page",
    lang: "العربية",
    footerEnd: "All rights reserved - My Ticket",
    mainPagePath: "Main Page",
    showsPagePath: "Events",
    ticketsTypes: "Tickets Types",
    selectTicketDefault: "Choose Ticket Type",
    chooseTicketDate: "Choose your favorable date :",
    chooseTicketTime: "Choose your favorable Time :",
    currency: "R.S",
    chooseDate: "Choose Date",
    chooseTiem: "Choose Time",
    chooseTicketsNumber: "Choose Tickets Number:",
    informationTab: "Event Information",
    description: "Description",
    bookNow: "Book Now",
    Saturday: "Saturday",
    Sunday: "Sunday",
    Monday: "Monday",
    Tuesday: "Tuesday",
    Wednesday: "Wednesday",
    Thursday: "Thursday",
    Friday: "Friday",
    fromHour: "From hour",
    toHour: "to hour",
    From: "From",
    to: "to",
    0: "Saturday",
    1: "Sunday",
    2: "Monday",
    3: "Tuesday",
    4: "Wednesday",
    5: "Thursday",
    6: "Friday",
    and: "and",
    bookingDate: "Booking date",
    from: "from",
    t: "to ",
    "00": "Saturday",
    11: "Sunday",
    22: "Monday",
    33: "Tuesday",
    44: "Wednesday",
    55: "Thursday",
    66: "Friday",
    startFrom: "Start from",
    until: "until",
    eventName: "Event Name",
    city: "City",
    date: "Date",
    time: "Time",
    address: "Address",
    organizer: "Organizer",
    rating: "Ratings",
    ChoosePayment: "Pay",
    done: "Done",
    cardNumber: "Card number",
    holderName: "Holder Name",
    expireDate: "Expire date",
    ticketPriceErrMessage: "Please Choose Error Type",
    chooseDateErrMEssage: "Please Choose Event Date",
    chooseSpecificTimeErrMessage: "Please Choose Event Time",
    chooseTicketCountErrMessage: "Please Choose Tickets Count",
    errMessage:
      "The stuff you were looking for doesn't exist or something wrong happened. Please try later",
    PromoCode: "Promo Code",
    PromoCodeErrMessage: "Please Enter Promo Code",
    loading: "Loading... ",
    Apply: "Apply",
    promoCodeSuccess: "Promo Code Applied Successfully",
  },
};

export default string;
